/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { ImageCreateNestedManyWithoutDishesInput } from "./ImageCreateNestedManyWithoutDishesInput";
import { VariantCreateNestedManyWithoutDishesInput } from "./VariantCreateNestedManyWithoutDishesInput";

@InputType()
class DishCreateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageCreateNestedManyWithoutDishesInput,
  })
  @ValidateNested()
  @Type(() => ImageCreateNestedManyWithoutDishesInput)
  @IsOptional()
  @Field(() => ImageCreateNestedManyWithoutDishesInput, {
    nullable: true,
  })
  images?: ImageCreateNestedManyWithoutDishesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => VariantCreateNestedManyWithoutDishesInput,
  })
  @ValidateNested()
  @Type(() => VariantCreateNestedManyWithoutDishesInput)
  @IsOptional()
  @Field(() => VariantCreateNestedManyWithoutDishesInput, {
    nullable: true,
  })
  variants?: VariantCreateNestedManyWithoutDishesInput;
}

export { DishCreateInput as DishCreateInput };
